version: '3.8'
services:
  frontend:
    build: ./frontend
    networks:
      - anime_net

  backend:
    build: ./backend
    networks:
      - anime_net

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token TU_TOKEN_DE_CLOUDFLARE_AQUI
    restart: always
    networks:
      - anime_net

networks:
  anime_net:
    driver: bridge
